---
title: 'Factorization Machine Code'
output:
  html_document:
    highlight: haddock
    number_sections: no
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
    toc_depth: '2'
date: "April 2021"
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse)
pacman::p_load(here)
pacman::p_load(lmtest)
pacman::p_load(glue)
pacman::p_load(broom)
pacman::p_load(ri2)
pacman::p_load(margins)
pacman::p_load(glmnet) 
pacman::p_load(kableExtra)
pacman::p_load(stargazer)
pacman::p_load(knitr)
pacman::p_load(doParallel)
pacman::p_load(corrplot)
pacman::p_load(corrplot)
pacman::p_load(rsparse)
pacman::p_load(recommenderlab)
pacman::p_load(reshape2)
pacman::p_load(ggplot2)
rm(list = ls())

# Note for 2021 data (coverage: 2020-05-01 to 2021-01-31): 
## filter60 means that we filtered out interactions involving
# children who made fewer than 60 interactions;
# after filtering, there are 11202 users left.
# This applies to both utils_mat_filtered.csv and utils_raw_filter60.csv.

story_info<- read_csv("Datasets/all_story_obs.csv")
utility_mat<- read_csv("Datasets/utils_mat_filtered.csv",col_types = cols(.default = col_double()))
set.seed(1992)
rows<-sample(1:nrow(utility_mat),size=5000)
utility_mat <- utility_mat[rows, ]
user_mapping <- utility_mat[,1:2]

source("../Utils/initialize_utility_matrix.R", local = knitr::knit_global())
initialization <- initialize_utility_matrix(utility_mat, story_info, 500)

utility_matrix <- initialization$utility_matrix
story_ids <- initialization$story_ids
child_ids <- initialization$child_ids

utils_raw_file <- "Datasets/utils_raw_filter60.csv"

# read story/user characteristics
story_info<- read_csv("Datasets/all_story_obs.csv")
user_info <- read_csv("Datasets/user_interests.csv")

# read child-story interaction data
utility_data_raw<-read_csv(utils_raw_file,col_types = cols(.default = col_double()))

story_attr <- c("totpage","wordcount","story_id_code","n_people")
user_attr <- c("i_Life_skills","grade", "user_id")
seed_value <- 123

# Note - below is the list of all parameters we will need to input
params<-list(raw_matrix=utility_data_raw, story_info=story_info,
             user_info=user_info, story_attr=story_attr, user_attr=user_attr,
             model_type="binomial", user_mapping = user_mapping
             , story_ids = story_ids, child_ids = child_ids,
             seed_value = seed_value)
```

Now to run the code - Factorization Machine

```{r}
source("../RecSys/get_item_scores.R", local = knitr::knit_global())
source("../RecSys/get_top_x_recommendations.R", local = knitr::knit_global())
FM_item_scores<-get_item_scores_generator(utility_matrix, "fm", params)
FM_top_X_recommendations<-function(userid, X, utility_matrix, story_ids){
  get_top_x_recommendations(userid, X, utility_matrix, FM_item_scores)
}

recs<-FM_top_X_recommendations(10, 5, utility_matrix)
```

Now to run the code - Random Model

```{r}
source("../RecSys/get_item_scores.R", local = knitr::knit_global())
source("../RecSys/get_top_x_recommendations.R", local = knitr::knit_global())
set.seed(123)
random_item_scores<-get_item_scores_generator(utility_matrix, "random")
random_top_X_recommendations<-function(userid, X, utility_matrix, story_ids){
  get_top_x_recommendations(userid, X, utility_matrix, story_ids, random_item_scores)
}
recs<-random_top_X_recommendations(10, 5, utility_matrix, story_ids)
recs
```
```{r}
# fm_get_factorization_matrix<-function(params){
#   
#   # Set up training data
#   utility_data_raw <- params$raw_matrix%>% filter(!is.na(intensity))
#   utility_data_raw <- utility_data_raw %>% rename(user_id = child_id_code)
#   
#   
#   # Set up test data
#   test_data <- expand.grid(user_id = params$child_ids, story_id_code = as.integer(params$story_ids))
#   
#   # Add item attributes to training data (if of interest)
#   if(!is.null(params$story_info)){
#     story_info_model <- story_info %>% select(one_of(params$story_attr))
#     merged_data_train <- left_join(utility_data_raw, story_info_model, by = c("story_id_code"="story_id_code")) %>% drop_na 
#     merged_data_test <- left_join(test_data, story_info_model, by = c("story_id_code"="story_id_code")) %>% drop_na 
#     utility_data_train <- merged_data_train
#     utility_data_test <- merged_data_test
#   }
#   
#   # Add user attributes to training data (if of interest)
#   if(!is.null(params$user_info)){
#     user_info <- params$user_info
#     user_info$grade<-as.integer(str_extract(user_info$grade,"[1-9]"))
#     user_info <- user_info %>% select(one_of(params$user_attr))
#     merged_data_train <-left_join(utility_data_train, user_info, by = c("user_id"="user_id")) %>% drop_na
#     merged_data_test <- left_join(utility_data_test, user_info, by = c("user_id"="user_id")) %>% drop_na
#   }
#   
#   #Now to train model and generate scores
#   factors <- append(params$story_attr, params$user_attr)
#   formula_fm <- as.formula(paste("intensity~", paste(factors, collapse="+")))
#   # Set up training data matrix form
#   train_matrix <- model.matrix(formula_fm, data = merged_data_train)
#   train_matrix_sparse = as(train_matrix, "RsparseMatrix")
#   if(params$model_type == "binomial"){
#     train_outcome <-ifelse(merged_data_train$intensity>0.4,1,0)
#   } else{
#     train_outcome <- merged_data_train$intensity
#   }
#   # Set up test data matrix form
#   merged_data_test$intensity <- 0.0
#   test_matrix <- model.matrix(formula_fm, data = merged_data_test)
#   
#   # run model
#   set.seed(params$seed_value)
#   fm = FactorizationMachine$new(learning_rate_w = 0.06, rank = 15, lambda_w = 0.001,
#                                 lambda_v = 0.001, family = params$model_type, intercept = FALSE)
#   res = fm$fit(train_matrix_sparse, train_outcome, n_iter = 50)
#   # New column with predictions for the test function
#   merged_data_test$preds = fm$predict(test_matrix)
#   # Normalize values to between 0 and 1
#   merged_data_test$preds <- (merged_data_test$preds - min(merged_data_test$preds)) / 
#     (max(merged_data_test$preds) - min(merged_data_test$preds))
#   merged_data_test
# }

test_function <- fm_get_factorization_matrix(params = params)
test_scores <- fm_get_item_scores(10, utility_matrix, test_function, params)
story_ids_test <-as.integer(colnames(utility_matrix))
# We need to remove items that they already know to from our recommendations.
user_row<-utility_matrix[10,]
unknown_stories<-user_row==0
names_unknown<-story_ids_test[unknown_stories]
  # unknown_stories_name <- names(unknown_stories[unknown_stories == TRUE])
  # index <- which(item_scores[unknown_stories_name] >= sort(item_scores[unknown_stories_name], decreasing=T)[X], arr.ind=TRUE)
index <- which(test_scores[unknown_stories] >= sort(test_scores[unknown_stories], decreasing=T)[5], arr.ind=TRUE)

# Eye test to compare
sort(test_scores, decreasing = TRUE)
names_unknown[index]
```

```{r}
source("../Utils/cross_validation_recsys.R", local = knitr::knit_global())
folds <- 10
X <- 5 # We will use precision at 5
type <- "fm"
params<-list(raw_matrix=utility_data_raw, story_info=story_info,
             user_info=user_info, story_attr=story_attr, user_attr=user_attr,
             model_type="binomial", user_mapping = user_mapping
             , story_ids = story_ids, child_ids = child_ids,
             seed_value = seed_value)
cross_validation_recsys(utility_matrix, folds, X, type, params)
```

```{r}
train_set <- utility_matrix
    valid_users <- which(splitfolds == 1)
    stories_removed <- list()
    for (userid in valid_users){
      user <- utility_matrix[userid,]
      index_of_known <- which(user!=0)
      if(length(index_of_known)>X){
        takeout <- sample(1:length(index_of_known),size=min(5, length(index_of_known)))
        stories_removed[[userid]] <- index_of_known[takeout]
        train_set[userid, stories_removed[[userid]]] <- 0
      }
    }
    
recommender <- get_item_scores_generator(utility_matrix, type, params)
precision_vector<-rep(NA,length(valid_users))
recall_vector<-rep(NA,length(valid_users))
rmse_vector<-rep(NA,length(valid_users))
```

```{r}
    for (userid in valid_users){
      user <- utility_matrix[userid,]
      index_of_known <- which(user!=0)
      if (length(index_of_known)>X) {
        recommended <- get_top_x_recommendations(userid, X, train_set, recommender)
        matched=length(intersect(story_ids[stories_removed[[userid]]],recommended))
        precision_vector[userid]<-(matched/X)
        recall_vector[userid]<-(matched/(length(index_of_known)))
        scores<-recommender(userid, train_set)
        scores[is.na(scores)]<-0.0
        rmse<-sqrt(mean((scores-utility_matrix[userid,])^2))
        rmse_vector[userid]<-rmse
      }
    }

test_users <- valid_users[1:10]
```
