---
title: 'Recommender Lab Test'
output:
  html_document:
    highlight: haddock
    number_sections: no
    theme: journal
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document:
    toc: yes
    toc_depth: '2'
date: "April 2021"
---

```{r setup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse)
pacman::p_load(here)
pacman::p_load(lmtest)
pacman::p_load(glue)
pacman::p_load(broom)
pacman::p_load(ri2)
pacman::p_load(margins)
pacman::p_load(glmnet) 
pacman::p_load(kableExtra)
pacman::p_load(recommenderlab)
pacman::p_load(stargazer)
pacman::p_load(knitr)
pacman::p_load(doParallel)
pacman::p_load(corrplot)
pacman::p_load(corrplot)
pacman::p_load(rsparse)
pacman::p_load(recommenderlab)
pacman::p_load(reshape2)
pacman::p_load(ggplot2)
rm(list = ls())

# Note for 2021 data (coverage: 2020-05-01 to 2021-01-31): 
## filter60 means that we filtered out interactions involving
# children who made fewer than 60 interactions;
# after filtering, there are 11202 users left.
# This applies to both utils_mat_filtered.csv and utils_raw_filter60.csv.

story_info<- read_csv("Datasets/all_story_obs.csv")
utility_mat<- read_csv("Datasets/utils_mat_filtered.csv",col_types = cols(.default = col_double()))
set.seed(1992)
rows<-sample(1:nrow(utility_mat),size=5000)
utility_mat <- utility_mat[rows, ]
user_mapping <- utility_mat[,1:2]

source("../Utils/initialize_utility_matrix.R", local = knitr::knit_global())
initialization <- initialize_utility_matrix(utility_mat, story_info, fill_zero = 0)

utility_matrix <- initialization$utility_matrix
story_ids <- initialization$story_ids
child_ids <- initialization$child_ids

utils_raw_file <- "Datasets/utils_raw_filter60.csv"

# read story/user characteristics
story_info<- read_csv("Datasets/all_story_obs.csv")
user_info <- read_csv("Datasets/user_interests.csv")

# read child-story interaction data
utility_data_raw<-read_csv(utils_raw_file,col_types = cols(.default = col_double()))

story_attr <- c("totpage","wordcount","story_id_code","n_people")
user_attr <- c("i_Life_skills","grade", "user_id")
seed_value <- 123

# Note - below is the list of all parameters we will need to input
params<-list(raw_matrix=utility_data_raw, story_info=story_info,
             user_info=user_info, story_attr=story_attr, user_attr=user_attr,
             model_type="binomial", user_mapping = user_mapping
             , story_ids = story_ids, child_ids = child_ids,
             seed_value = seed_value)
```


```{r test models}
num_nonNA <- nnzero(utility_matrix, na.counted = FALSE)
num_entries <- dim(utility_matrix)[1] * dim(utility_matrix)[2]
(num_entries - num_nonNA) / num_entries
utility_matrixRM <- as(utility_matrix, "realRatingMatrix")
```
```{r}
#test_matrix <- utility_matrix[rowSums(utility_matrix, na.rm=T) > 0,]
test_matrix <- utility_matrix[!is.na(rowSums(utility_matrix, na.rm = TRUE) * NA ^ (rowSums(!is.na(utility_matrix)) == 0)),]
utility_matrixRM <- as(test_matrix, "realRatingMatrix")
```


```{r}
eval_scheme <- recommenderlab::evaluationScheme(utility_matrixRM,
  method = "split",
  train = 0.7, given = 1, goodRating = 0.3)

# item-based nearest neighbors using cosine similarity
IBCF_model <- recommenderlab::Recommender(
  recommenderlab::getData(eval_scheme, "train"),
  method = "IBCF"
)

# used-based nearest neighbors using cosine similarity
UBCF_model <- recommenderlab::Recommender(
  recommenderlab::getData(eval_scheme, "train"),
  method = "UBCF"
)

# Funk SVD algorithm
SVD_model <- recommenderlab::Recommender(
  recommenderlab::getData(eval_scheme, "train"),
  method = "SVDF", param = list(k = 5)
)
```

```{r}
# Get predicted ratings for all items

## Predicted values from item-based model
pred_IBCF <- predict(IBCF_model,
  recommenderlab::getData(eval_scheme, "known"),
  type = "ratings", n = c(1)
)

## Predicted values from user-based model
pred_UBCF <- predict(UBCF_model,
  recommenderlab::getData(eval_scheme, "known"),
  type = "ratings", n = c(1)
)

## Predicted values from SVD model
pred_svd <- predict(SVD_model,
  recommenderlab::getData(eval_scheme, "known"),
  type = "ratings", n = c(1)
)
```


```{r}
data(MovieLense)
ratings_matrix <- MovieLense
```